import { prisma } from "@bigwing/db";

async function fixDates() {
  console.log("Fetching historical Meta leads...");
  
  // Find all leads generated by the historical sync script
  const historicalLeads = await prisma.lead.findMany({
    where: {
      channel: "SOCIAL",
      remark: {
        contains: "Historical Meta Lead ID"
      }
    },
    select: { id: true, enquiryDate: true }
  });

  console.log(`Found ${historicalLeads.length} historical leads to fix.`);

  let count = 0;
  for (const lead of historicalLeads) {
    // We use a raw query because Prisma usually blocks manual updates to @default(now()) fields
    await prisma.$executeRaw`
      UPDATE core.lead 
      SET created_at = ${lead.enquiryDate} 
      WHERE id = ${lead.id}
    `;
    
    count++;
    if (count % 500 === 0) {
      console.log(`Updated ${count} leads...`);
    }
  }

  console.log("✅ Successfully updated all historical lead timestamps!");
}

fixDates()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
