import { prisma } from "@bigwing/db";

async function fixDates() {
  console.log("Fetching historical Meta leads...");
  
  // Find all leads generated by the historical sync script
  const historicalLeads = await prisma.lead.findMany({
    where: {
      channel: "SOCIAL",
      remark: {
        contains: "Historical Meta Lead ID"
      }
    },
    select: { id: true, enquiryDate: true }
  });

  console.log(`Found ${historicalLeads.length} historical leads to fix.`);

  let count = 0;
  for (const lead of historicalLeads) {
    // Because Facebook returns the newest leads first, the Newest leads got the Lowest IDs.
    // The CRM UI sorts by enquiryDate DESC, then createdAt DESC.
    // enquiryDate has no time component in the database.
    // To make the Newest leads appear at the top, we need them to have the HIGHEST createdAt.
    // We achieve this by adding (1,000,000 - ID) seconds to their enquiryDate.
    
    const baseTime = lead.enquiryDate.getTime();
    const syntheticTime = baseTime + (1000000 - Number(lead.id)) * 1000;
    const newCreatedAt = new Date(syntheticTime);

    await prisma.$executeRaw`
      UPDATE core.lead 
      SET created_at = ${newCreatedAt} 
      WHERE id = ${lead.id}
    `;
    
    count++;
    if (count % 500 === 0) {
      console.log(`Updated ${count} leads...`);
    }
  }

  console.log("✅ Successfully updated all historical lead timestamps!");
}

fixDates()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
